name: whakaaribn
channels:
    - pytorch
    - ankurankan
    - plotly
    - conda-forge
dependencies:
    - python=3.10
    - cartopy
    - ipykernel
    - ipywidgets
    - matplotlib
    - numpy<=2.1
    - pandas
    - plotly
    - python-kaleido
    - seaborn
    - scikit-learn
    - scipy
    - statsmodels
    - pytest
    - tqdm
    - nbformat
    - nbconvert
    - pytest-cov
    - pytorch
    - cpuonly
    - pgmpy
    - netcdf4
    - xarray
    - pymc
    - pip
    - pip:
        - schedule==1.1
        - tonik>=0.0.10
        - owslib
        - aitana
        - httpx